### ISSUE TITLE
Can't install https://www.nuget.org/packages/Microsoft.VisualStudio.Sdk.TestFramework

### ISSUE THREAD

**Issue by maysonchen-cs** [microsoft/vssdktestfx#26] opened 2022-04-05 04:56 UTC
I try to install this package  <PackageReference Include="Microsoft.VisualStudio.Sdk.TestFramework" Version="17.0.15" />. However, it always reports 
`
Restoring packages for C:\Users\xxxx\source\repos\ImageOptimizer\Test\ImageOptimizer.Test\ImageOptimizer.Test.csproj...
  GET https://api.nuget.org/v3-flatcontainer/microsoft.internal.visualstudio.interop/index.json  
  NotFound https://api.nuget.org/v3-flatcontainer/microsoft.internal.visualstudio.interop/index.json 1085ms  

NU1101: Unable to find package **Microsoft.Internal.VisualStudio.Interop.** No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org  

Package restore failed. Rolling back package changes for 'ImageOptimizer.Test'.  

Time Elapsed: 00:00:01.6479626  
`

**Comment by AArnott** [comment] 2022-04-05 12:29
Duplicate of #9

**Closed by AArnott** 2022-04-05 12:29 UTC
